/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as Analytics_backupRouteImport } from './routes/analytics_backup'
import { Route as ApiManagementRouteImport } from './routes/api-management'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as NewWorkflowRouteImport } from './routes/new-workflow'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const Analytics_backupRoute = Analytics_backupRouteImport.update({
  id: '/analytics_backup',
  path: '/analytics_backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManagementRoute = ApiManagementRouteImport.update({
  id: '/api-management',
  path: '/api-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const NewWorkflowRoute = NewWorkflowRouteImport.update({
  id: '/new-workflow',
  path: '/new-workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/analytics_backup': typeof Analytics_backupRoute
  '/api-management': typeof ApiManagementRoute
  '/approvals': typeof ApprovalsRoute
  '/brain': typeof BrainRoute
  '/new-workflow': typeof NewWorkflowRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/analytics_backup': typeof Analytics_backupRoute
  '/api-management': typeof ApiManagementRoute
  '/approvals': typeof ApprovalsRoute
  '/brain': typeof BrainRoute
  '/new-workflow': typeof NewWorkflowRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/analytics_backup': typeof Analytics_backupRoute
  '/api-management': typeof ApiManagementRoute
  '/approvals': typeof ApprovalsRoute
  '/brain': typeof BrainRoute
  '/new-workflow': typeof NewWorkflowRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/analytics'
    | '/analytics_backup'
    | '/api-management'
    | '/approvals'
    | '/brain'
    | '/new-workflow'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/analytics'
    | '/analytics_backup'
    | '/api-management'
    | '/approvals'
    | '/brain'
    | '/new-workflow'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/analytics'
    | '/analytics_backup'
    | '/api-management'
    | '/approvals'
    | '/brain'
    | '/new-workflow'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  Analytics_backupRoute: typeof Analytics_backupRoute
  ApiManagementRoute: typeof ApiManagementRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BrainRoute: typeof BrainRoute
  NewWorkflowRoute: typeof NewWorkflowRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics_backup': {
      id: '/analytics_backup'
      path: '/analytics_backup'
      fullPath: '/analytics_backup'
      preLoaderRoute: typeof Analytics_backupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-management': {
      id: '/api-management'
      path: '/api-management'
      fullPath: '/api-management'
      preLoaderRoute: typeof ApiManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-workflow': {
      id: '/new-workflow'
      path: '/new-workflow'
      fullPath: '/new-workflow'
      preLoaderRoute: typeof NewWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  Analytics_backupRoute: Analytics_backupRoute,
  ApiManagementRoute: ApiManagementRoute,
  ApprovalsRoute: ApprovalsRoute,
  BrainRoute: BrainRoute,
  NewWorkflowRoute: NewWorkflowRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
